@startuml
'https://plantuml.com/class-diagram

Solution45 <-- FileManager
Solution45 <-- WordFinder


class Solution45 {
    userInput()
    outputFile()
}

enum FileManager {
    inputFile()
}

enum WordFinder {
    replaceWords()
    changeWord()
}

@enduml