@startuml
'https://plantuml.com/class-diagram

Solution42 <-- FileManager
FileManager <-- ListParser

class Solution42 {
    userInput()
    generateOutput()
}

enum FileManager {
    readFile()
}

enum ListParser {
    parseList()
}

@enduml